name: D_OCBS
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.2.1
  intl: ^0.19.0

  # ⭐ Only these TWO Bluetooth libs allowed
  blue_thermal_printer: ^1.2.0
  flutter_bluetooth_serial: ^0.4.0

  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  image: ^4.1.7
  mobile_scanner: ^3.5.0
  socket_io_client: ^2.0.3

dependency_overrides:
  flutter_blue: any
  flutter_blue_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/logo.png

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
